# Generated by Django 4.2.6 on 2023-10-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_parentchild_childes'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='childes',
            field=models.ManyToManyField(blank=True, related_name='childes', to='system.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.menu'),
        ),
        migrations.DeleteModel(
            name='ParentChild',
        ),
    ]
