# Generated by Django 4.2.6 on 2023-10-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_menu_childes_menu_parent_delete_parentchild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='childes',
        ),
    ]
